### ISSUE TITLE
Bug in tests

### ISSUE THREAD

**Issue by sobolev-igor** [rhlsthrm/typescript-solidity-dev-starter-kit#1]
Hi! Thanks for the repo!

I've tried to run tests, but the second one fails [here](https://github.com/rhlsthrm/typescript-solidity-dev-starter-kit/blob/1ee12a686c5f5eba8748d4fdf6ce4be5117a4317/test/counter.ts#L43), as `count` variable of `Counter` contract is set to 0 inside the `beforeEach()` call. Therefore, `countDown()` function call reverts! 

You should add `countUp()` function call before counting down :)

**Comment by rhlsthrm** [comment]
Hey @sobolev-igor! The test actually errors on purpose to show the power of the Solidity stack traces that Buidler enables! I should make a note of this. Thanks for the feedback!

**Comment by rhlsthrm** [comment]
https://github.com/rhlsthrm/typescript-solidity-dev-starter-kit/blob/master/README.md#run-contract-tests

I've updated the README to reflect!

**Comment by sobolev-igor** [comment]
Oh, I got it!
