### ISSUE TITLE
Tests don't fail like README says they should

### ISSUE THREAD

**Issue by feuGeneA** [rhlsthrm/typescript-solidity-dev-starter-kit#27]
The README says: "As is, the tests fail on purpose. This is to show the Solidity stack traces that Hardhat enables!"

However, I followed the instructions in the README, and the tests did not fail: ![image](https://user-images.githubusercontent.com/7883777/123176594-f34f7b80-d440-11eb-93d8-97312db60dec.png)

**Comment by rhlsthrm** [comment]
I did it like that initially, but people did not like the failing tests in the project so we modified it.
